### ISSUE TITLE
prog-mode only

### ISSUE THREAD

**Issue by blaenk** [blorbx/evil-quickscope#2]
It'd probably be pretty cool if you could have an option so that it only enabled/highlighted on non-comments, if that makes any sense. Like the reverse of flyspell-prog-mode.

**Comment by PythonNut** [comment]
This sounds pretty weird. What happens if you want to navigate inside of comments?

**Comment by blaenk** [comment]
Then you wouldn't use this mode. Same as with flyspell-prog-mode. What happens if you want to spell check code too? Then you wouldn't use flyspell-prog-mode, you'd use regular flyspell-mode.

**Comment by PythonNut** [comment]
This should work:

``` emacs
(with-eval-after-load 'evil-quickscope
  (defun nadvice/evil-quickscope-update-overlays-bidirectional (old-fun)
    "Update overlays in both directions from point."
    (evil-quickscope-remove-overlays)
    (unless (nth 4 (syntax-ppss))
      (evil-quickscope-apply-overlays-forward)
      (evil-quickscope-apply-overlays-backward)))

  (advice-add
    'evil-quickscope-update-overlays-bidirectional
    :around
    #'nadvice/evil-quickscope-update-overlays-bidirectional))
```

**Comment by blorbx** [comment]
Thanks, I used your implementation behind a new parameter: `evil-quickscope-disable-in-comments`.

**Comment by PythonNut** [comment]
:D
