### ISSUE TITLE
Respect evil-cross-lines

### ISSUE THREAD

**Issue by PythonNut** [blorbx/evil-quickscope#3]
It would be great if `evil-quickscope` could highlight characters across lines. You could do this by introducing a new parameter `evil-quickscope-cross-lines` and having it default to `evil-cross-lines`.

**Comment by blorbx** [comment]
Added a parameter for this, `evil-quickscope-cross-lines`. Decided to default it `nil` instead of `evil-cross-lines` as it might be unpredictable defaulting on another parameter.

**Comment by PythonNut** [comment]
Cool, thanks.
