### ISSUE TITLE
[Feature Request] multi-line support

### ISSUE THREAD

**Issue by Dewdrops** [blorbx/evil-quickscope#8]
Thanks for the useful extension !
I'm a big fan of the original vim-quickscope plugin, and very happy to see it ported to Evil.
Evil's `f`, `F`, `t`, `T`, `,`, `;` can be customized to cross newlines by setting `evil-cross-lines` to `t`. I think it would be wonderful if evil-quickscope can also highlight targets across newlines in that situation.

**Comment by blorbx** [comment]
You should be able to achieve this with the `evil-quickscope-cross-lines` parameter:
`(setq evil-quickscope-cross-lines t)`

**Comment by Dewdrops** [comment]
Sorry for my silly question. I did not noticed that parameter.
Thx. Works great.
